/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TP_H_RPCGEN
#define _TP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXPARAMNAME 1000000

typedef char *name;
#define MAXNAMELEN 255

typedef char *comando;

struct tp_info {
	comando grep_args;
	name data;
};
typedef struct tp_info tp_info;

#define TP_PROG 0x03071988
#define TP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TP_PROC 1
extern  char ** tp_proc_1(struct tp_info *, CLIENT *);
extern  char ** tp_proc_1_svc(struct tp_info *, struct svc_req *);
#define TP_EXIT 2
extern  void * tp_exit_1(struct tp_info *, CLIENT *);
extern  void * tp_exit_1_svc(struct tp_info *, struct svc_req *);
#define TP_STATUS 3
extern  int * tp_status_1(struct tp_info *, CLIENT *);
extern  int * tp_status_1_svc(struct tp_info *, struct svc_req *);
extern int tp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TP_PROC 1
extern  char ** tp_proc_1();
extern  char ** tp_proc_1_svc();
#define TP_EXIT 2
extern  void * tp_exit_1();
extern  void * tp_exit_1_svc();
#define TP_STATUS 3
extern  int * tp_status_1();
extern  int * tp_status_1_svc();
extern int tp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name (XDR *, name*);
extern  bool_t xdr_comando (XDR *, comando*);
extern  bool_t xdr_tp_info (XDR *, tp_info*);

#else /* K&R C */
extern bool_t xdr_name ();
extern bool_t xdr_comando ();
extern bool_t xdr_tp_info ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TP_H_RPCGEN */
